### ISSUE TITLE
Encoding & decoding https://example.com returns extra character

### ISSUE THREAD

**Issue by adriaandotcom** [g-plane/simple-base#1]
Awesome project, thanks for making this.

I found a glitch though. When I run this code:

```js
const SimpleBase = require('simple-base');

const string = 'https://example.com';
const encoded = SimpleBase.encode(string, 36);
const decoded = SimpleBase.decode(encoded, 36);

console.log('before', string, string.length); // before https://example.com 19
console.log('after', decoded, decoded.length); // after https://example.com 20
```

It returns a different string when encoding the string `https://example.com` and decoding it back. There seems to be a weird character at the start of the decoded string.

If I run `decoded.slice(0, 4)` it returns ` htt` (but not with a space but some other character.

**Comment by g-plane** [comment]
You are right. I have reproduced this bug.

**Comment by adriaandotcom** [comment]
Awesome, thanks! I'm using your library here: https://dnsforwarding.com

**Comment by lzjluzijie** [comment]
We are doing the same thing lol @adriaanvanrossum
